# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "coverage"
  coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    ###### a real life use
    - name: Set up Python 3.9
      uses: actions/setup-python@v2.3.0
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
        
    - name: Run tox for coverage report
      run: |
        tox -e coverage
        
    - name: Upload to Codecov
      # Skip step on forked repos
      if: github.repository == 'ger88555/crism-tts'
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: pytests
        file: ./app/tests/coverage.xml
        fail_ci_if_error: true
        
    ###### use suggested by codecov
#     steps:
#     - uses: actions/checkout@master
#     - uses: codecov/codecov-action@v2
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         files: ./coverage1.xml,./coverage2.xml # optional
#         flags: unittests # optional
#         name: codecov-umbrella # optional
#         fail_ci_if_error: true # optional (default = false)
#         verbose: true # optional (default = false)
